apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-web-app
spec:
  selector:
    matchLabels:
      name: hr-web-app
  template:
    metadata:
      name: hr-web-app
      labels:
        name: hr-web-app
    spec:
      containers:
        - name: hr
          image: kodekloud/webapp-color
  replicas: 2
