apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper
  namespace: default
spec:
  containers:
  - command:
    - sleep
    - "3600"
    image: ubuntu
    name: ubuntu
    securityContext:
      runAsUser: 0
      capabilities:
        add:
          - "SYS_TIME"