apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
    - image: kodekloud/event-simulator
      name: event-simulator
      volumeMounts:
      - mountPath: /log
        name: log-pvc
  volumes:
    - name: log-pvc
      persistentVolumeClaim:
        claimName: claim-log-1
