apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-log
  labels:
    app: webapp
spec:
  capacity:
    storage: 100Mi
  hostPath:
    path: /pv/log
    type: Directory
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-log-1
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Mi
  selector:
    matchLabels:
      app: webapp
