apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storage-admin
rules:
  - verbs:
      - get
      - list
      - create
      - delete
    apiGroups:
      - pv
    resources:
      - persistentvolumes
  - verbs:
      - get
      - list
      - create
      - delete
    apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses