apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: new-replica-set
  labels:
    name: new-replica-set

spec:
  selector:
    matchLabels:
      name: busybox-pod
  replicas: 4
  template:
    metadata:
      name: busybox-pod
      labels:
        name: busybox-pod

    spec:
      containers:
        - name: busybox
          image: busybox
          args:
            - sleep
            - "1000000"