apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    name: nginx-rs

spec:
  selector:
    matchLabels:
      name: nginx-pod
  replicas: 3
  template:
    metadata:
      name: nginx-pod
      labels:
        name: nginx-pod
    spec:
      containers:
        - name: nginx
          image: nginx