apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: front-end

spec:
  selector:
    matchLabels:
      type: webserver
  replicas: 3
  template:
    metadata:
      name: nginx-pod
      labels:
        type: webserver
        app: myapp

    spec:
      containers:
        - name: nginx-container
          image: nginx